// Reads src/audio-processor.js and emits src/worklet-source.ts exporting the
// contents as a string constant, so the SDK can register the AudioWorklet
// via a Blob URL at runtime — no separate asset hosting needed.

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const srcPath = resolve("src/audio-processor.js");
const outPath = resolve("src/worklet-source.ts");

const source = readFileSync(srcPath, "utf8");

const out = `// AUTO-GENERATED by scripts/embed-worklet.mjs. Do not edit by hand.
// Regenerated from src/audio-processor.js on every build.
export const WORKLET_SOURCE = ${JSON.stringify(source)};
`;

writeFileSync(outPath, out);
console.log(`[embed-worklet] wrote ${outPath} (${source.length} chars)`);
